config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  post '/call', to: 'twilio#call', as: 'call'
  post '/twilio/voice' => 'twilio#voice'
  post '/connect/:target_phone/', to: 'twilio#connect', as: 'connect'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_civic_api.rb
class GoogleCivicApi < ApplicationRecord

  attr_accessor :data

  def self.find_representative_by_address(address)
    HTTParty.get( 
      "https://www.googleapis.com/civicinfo/v2/representatives?key=
      #{Rails.application.secrets.google_api_key}&address=#{address}",
     :headers =>{'Content-Type' => 'application/json'} 
    )
  end
end

app/models/twilio_contact.rb
# Simple model to handle validation
class TwilioContact
  include ActiveModel::Validations
  attr_accessor :user_phone
  attr_accessor :target_phone
  validates_presence_of :user_phone
  validates_presence_of :target_phone

  def encoded_target_phone
    URI.encode(target_phone)
  end
end

app/models/user.rb
class User < ApplicationRecord

  def self.create_with_omniauth(auth)
    create! do |user|
      Rails.logger.info "-----------------------------------"
      Rails.logger.info "Executing User.create_with_omniauth."
      Rails.logger.info auth
      Rails.logger.info "-----------------------------------"
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['credentials']
        user.token = auth['credentials']['token']
        user.token_expires_at = Time.at(auth['credentials']['expires_at'])
      end

      if auth['info']
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email'] || ""
        user.image = auth['info']['image'] || ""
      end
    end
  end

  def facebook
    @facebook ||= Koala::Facebook::API.new(token)
    block_given? ? yield(@facebook) : @facebook
  rescue Koala::Facebook::APIError => e
    logger.info e.to_s
    nil # or consider a custom null object
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    reset_session
    session[:user_id] = user.id
    redirect_to root_url, :notice => 'Signed in!'
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/twilio_controller.rb
class TwilioController < ApplicationController

  # Before we allow the incoming request to connect, verify
  # that it is a Twilio request
  before_action :load_credentials, only: [:call, :connect]
  before_action :authenticate_twilio_request, only: [:connect]
  skip_before_action :verify_authenticity_token



  # Handle a POST from our web form and connect a call via REST API
  def call
    twilio_contact = TwilioContact.new
    twilio_contact.user_phone  = params[:userPhone]
    twilio_contact.target_phone = params[:targetPhone]

    # Validate contact
    if twilio_contact.valid?
      @client = Twilio::REST::Client.new @twilio_sid, @twilio_token
      # Connect an outbound call to the number submitted
      @call = @client.calls.create(
        to:   twilio_contact.user_phone,
        from: Rails.application.secrets.twilio_phone_number,
        url: "https://salty-citadel-43320.herokuapp.com/connect/#{twilio_contact.encoded_target_phone}"
        # url: "http://localhost:3000/connect/1"
      )

      # Let's respond to the ajax call with some positive reinforcement
      @msg = { message: 'Phone call incoming!', status: 'ok' }
    else

      # Oops there was an error, lets return the validation errors
      @msg = { message: twilio_contact.errors.full_messages, status: 'ok' }
    end

    # respond_to do |format|
    #   format.json { render json: @msg }
    # end
    # format.json { render json: @msg }
    redirect_to user_path(current_user)
  end

  # This URL contains instructions for the call that is connected with a lead
  # that is using the web form.
  def connect
    Rails.logger.info "TwilioController.connect"
    # Our response to this request will be an XML document in the "TwiML"
    # format. Our Ruby library provides a helper for generating one
    # of these documents
    response = Twilio::TwiML::VoiceResponse.new do |r|
      r.say('Thanks for contacting our sales department. Our '\
        'next available representative will take your call.', voice: 'alice')
      r.dial number: params[:target_phone]
    end


    render xml: response.to_s
  end

  # Authenticate that all requests to our public-facing TwiML pages are
  # coming from Twilio. Adapted from the example at
  # http://twilio-ruby.readthedocs.org/en/latest/usage/validation.html
  # Read more on Twilio Security at https://www.twilio.com/docs/security
  private

  def authenticate_twilio_request
    return true
    # if twilio_req?
    #   return true
    # else
    #   response = Twilio::TwiML::VoiceResponse.new do|r|
    #     r.hangup
    #   end

    #   render xml: response.to_s, status: :unauthorized
    #   false
    # end
  end

  def twilio_req?
    # Helper from twilio-ruby to validate requests.
    validator = Twilio::Security::RequestValidator.new(@twilio_token)

    # the POST variables attached to the request (eg "From", "To")
    # Twilio requests only accept lowercase letters. So scrub here:
    post_vars = params.reject { |k, _| k.downcase == k }
    twilio_signature = request.headers['HTTP_X_TWILIO_SIGNATURE']

    validator.validate(request.url, post_vars, twilio_signature)
  end

  def load_credentials
    # Define our Twilio credentials as instance variables for later use
    @twilio_sid = ENV['TWILIO_ACCOUNT_SID']
    @twilio_token = ENV['TWILIO_AUTH_TOKEN']
    @twilio_number = ENV['TWILIO_NUMBER']
    @api_host = ENV['API_HOST']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    
    @civicInfo = GoogleCivicApi.find_representative_by_address(@user.address)

  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :image, :token,
                                   :address, :phone)
    end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twilio_helper.rb
module TwilioHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Sign out', signout_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Users', users_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Settings', edit_user_path(current_user), class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', signin_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <%= render 'layouts/navigation_links' %>
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<!--<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Smg Advocacy" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Smg Advocacy" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>

    <%= javascript_include_tag "application" %>
    
    <script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCy_CoKZ76VKms6eFQ9rz7BsQY57NVSIqc"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/popper.min.js"></script>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>

<h3>About the Website</h3>
<p>
  Who is your State Senator?
</p>
<p>
  I’ll betcha don’t know.
</p>
<p>
  When I realized that I didn't know who mine was, I was kind of surprised. You see, I’m a fairly engaged citizen and have been politically for over 15 years. I am engaged enough to follow news from multiple sources just to make sure I hear from all sides of the story. 
</p>
<p>
  But, I didn't even know who my local State Senator was and I wanted to understand why. 
</p>
<p>
  One reason is that the vast majority of news from major sources is focused on national issues, not state and local. However, the things that impact me most in terms of day-to-day life are local. 
</p>
<p>
  That seems a bit backwards to me.
</p>
<p>
  ----
</p>
<p>
  Another thing that seems broken in our current system is the ratio of signal to noise in the information we consume. 
</p>
<p>
  In the era of 24/7 news sensationalism is more important than truth. "News" devolves into pundits from opposite ends of the political spectrum yelling at each other to create tension and elicit emotional responses from viewers. 
</p>
<p>
  It really is just entertainment under the guise of news. I don't think "Fake News" is a thing in a literal sense, but you'd have to be pretty naieve to not understand why the phrase stuck. 
</p>
<p>
  ----
</p>
<p>
  Wanting to reduce the signal-to-noise ratio, I thought: "Why not just go straight to the source?" In this case, the "source" is the set of people who represent you in governemnt. Figuring out who those people are is the first step in changing the government.
</p>
<p>
  Enter your address and phone number here and I’ll use your address to search Google Civic API to show you everyone that represents you in the United States government.
</p>
<p>
  [[ FORM ]]
</p>
<p>
  [[ SHOWS UP AFTER THEY CLICK SUBMIT ]]
</p>
<p>
  Now that we know who represents us, we should orient ourselves to what they do. Again, let’s just go straight to the source. Who do you want to follow? 
</p>
<p>
  [[ GALLARY OF OFFICIALS ]]
</p>
<p>
            Name, 
            Official Title,
            Poltical Party
</p>
<p>
  Next, select your favorite platforms and we'll automatically connect you to them so you know what they are up to.
</p>
<p>
  [[FB, Instagram, Twitter, Snapchat, Email Newsletter]]
</p>
<p>
  ----
</p>
<p>
  News sources still have their purpose! 
</p>
<p>
  Politicians will always spin things to paint themselves in the best light, so I want some third-party analysis. And I’m sure you do too. But, I don’t want to be inundated with all their noise and banter. I want to regulate the flow of information.
</p>
<p>
  The first step is deciding where you want to source your third-party analysis. I encourage you to subscribe to at least one or two that you aren't used to, just for a little diversity of thought.
</p>
<p>
  [[List of News Sites]]
</p>
<p>
  Next, what issues do you care about and how much do you care about each issue? This will help us prioritize getting you the news you care most about.
</p>
<p>
  [[Drag and Drop Issues from List to Pie Chart with editable allocation percentages]]
</p>
<p>
  Finally, how often do you want to be notified about the latest news - from every minute of every hour to a monthly summary and everything in between. 
</p>
<p>
  [[Select delivery frequency]]
</p>
<p>
  ----
</p>
<p>
  It's one thing to know what people are saying - but an entirely different thing to know how people are voting. 
</p>
<p>
  So, I also made nifty toolbar that shows you how your representative voted on bills you care about. 
</p>
<p>
  I didn't want it to be annoying, so it only shows up when you're on a social media or news website - when I care the most.
</p>
<p>
  [[Download Toolbar]]
</p>
<p>
  The toolbar makes it super easy to see how your elected officials are voting on bills related to issues you care about. 
</p>
<p>
  It also lets you call your elected official with a single click. If you like how they voted then you can call and tell them to keep up the good work! Trust me, they love hearing how good of a job they are doing. 
</p>
<p>
  And, if your elected official voted differently than how you want, make sure they know that too!
</p>
<p>
  It’s amazing how much time I spent posting about the news of the day on social media contrasted to how little time I actually spent doing anything. Now I can talk about what I did rather than merely complain and troll random strangers online.
</p>
<p>
  [[Share on Social Media buttons]]
</p>
<p>
  ----
</p>
<p>
  If that elected official still isn't stepping up it might be time to replace them. 
</p>
<p>
  In order to do that it's important to [[register to vote]]
</p>
<p>
  The toolbar will give you a notice when elections are coming up so you can get involved, donate, or maybe even run for something yourself!
</p>
<p>
  And, of course, we'll remind you when and where to vote. :)
</p>
<p>
  ----
</p>
<p>
  The last feature of the toolbar is meant to give you a voice.
</p>
<p>
  Congress has something like a 7% approval rating. Nearly all Americans agree that government is so polarized and partisan that it’s basically worthless. This makes us look stupid in the eyes of the world and Americans are smarter than that. 
</p>
<p>
  We agree on vastly more than we disagree on.
</p>
<p>
  The toolbar lets each person cast a single anonymous and public vote, and make a single statement on any issue they want.
</p>
<p>
  You can change your vote at any time. In fact, we encourage it. Soak in new information. Question assumptions. You should be discussing issues with friends, staying informed, ane evolving your perspectives. 
</p>
<p>
  Votes are recorded on the blockchain. So, you get all the security and privacy features along with the benefit of a decentralized system.
</p>
<p>
  Voter sentiment can be filtered and grouped by congressional district, state, national levels, as well as by political party. The full spectrum of political thought can be put on display through a signle statement that each voter is able to make when casting their vote.
</p>
<p>
  With widespread adoption and sufficient identity management, we could build an authoritative and decentralized voter sentiment model available to the public domain. 
</p>
<p>
  We can show the world that “we the people", on a district by district level, aren't as stupid as our government and political environment currently makes us look. 
</p>
<p>
  We are unified on most issues, and through this technology, we can prove it.
</p>
<p>
  ----
</p>
<p>
  VISION OF THE FUTURE
</p>
<p>
  This underlying technology has applications outside the political space. 
</p>
<p>
  Applying blockchain technology to voting system is an ideal use case that is issue agnostic and scales well. It works just as well electing a youth soccer team coach as it does the President of the United States. 
</p>
<p>
  Americans will insist on an online voting system in the future. An online voting platform with a proven track record and established goodwill with the public will be well positioned as an authoritative vendor to provide that solution.
</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control', :disabled => true %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control', :disabled => true %>

  <%= f.label :address %>
  <%= f.text_field :address, class: 'form-control', placeholder: 'Start typing an address...' %>  

  <%= f.label :phone %>
  <%= f.text_field :phone, class: 'form-control' %>

  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<td><p class="text-left"><%= link_to user.name, user %></p></td>
<td><p class="text-left"><%= user.email %></p></td>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>

<h1>Update your profile</h1>
<img src="<%= @user.image %>">
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User Details') %>

<h1>User Details</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= image_tag(@user.image) %>
    <p>Name: <%= @user.name if @user.name %></p>
    <p>Email: <%= @user.email if @user.email %></p>
    <p>Address: <%= @user.address if @user.address %></p>
    <p>Phone: <%= @user.phone if @user.phone %></p>

    <p>Facebook OAuth Token: <%= @user.token if @user.token %></p>
    <p>Image URL: <%= @user.image if @user.image %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% @civicInfo["divisions"].each do |division| %>
      <% division[1]["officeIndices"].each do |office_index| %>
        <% office = @civicInfo["offices"][office_index] %>
        
        <% office["officialIndices"].each do |official_index| %>
          <% official = @civicInfo["officials"][official_index] %>
        
          
          <h3><%= official["name"] %></h3>
          <p><%= office["name"] %>, <%= official["party"] %></p>
          <!-- <p>
            <%= official["address"][0]["line1"] %><br>
            <%= official["address"][0]["line2"] %><br>
            <%= official["address"][0]["city"] %><br>
            <%= official["address"][0]["state"] %><br>
            <%= official["address"][0]["zip"] %>
          </p>
          <p><%= official["phones"][0] %></p> -->

          <%= form_tag("/call", method: "post") do %>
            <%= label_tag(:userPhone, "User Phone:") %>
            <%= text_field_tag(:userPhone, @user.phone) %>
            <br/>
            <%= label_tag(:targetPhone, "Legislator Phone:") %>
            <%= text_field_tag(:targetPhone, official["phones"][0] ) %>
            <br/>
            <%= submit_tag("Call") %>
          <% end %>
          
        <% end %>  
      <% end %>  
    <% end %>
  </div>
</div>

app/views/visitors/index.html.erb
<% content_for :title do %>SMG Advocacy<% end %>

<h3>Why I made this site</h3>
<p>
  Who is your State Senator?
</p>
<p>
  I’ll betcha don’t know.
</p>
<p>
  When I realized that I didn't know who mine was, I was kind of surprised. You see, I’m a fairly engaged citizen and have been politically for over 15 years. I am engaged enough to follow news from multiple sources just to make sure I hear from all sides of the story. 
</p>
<p>
  But, I didn't even know who my local State Senator was and I wanted to understand why. 
</p>
<p>
  One reason is that the vast majority of news from major sources is focused on national issues, not state and local. However, the things that impact me most in terms of day-to-day life are local. 
</p>
<p>
  That seems a bit backwards to me.
</p>
<p>
  ----
</p>
<p>
  Another thing that seems broken in our current system is the ratio of signal to noise in the information we consume. 
</p>
<p>
  In the era of 24/7 news sensationalism is more important than truth. "News" devolves into pundits from opposite ends of the political spectrum yelling at each other to create tension and elicit emotional responses from viewers. 
</p>
<p>
  It really is just entertainment under the guise of news. I don't think "Fake News" is a thing in a literal sense, but you'd have to be pretty naieve to not understand why the phrase stuck. 
</p>
<p>
  ----
</p>
<p>
  Wanting to reduce the signal-to-noise ratio, I thought: "Why not just go straight to the source?" In this case, the "source" is the set of people who represent you in governemnt. Figuring out who those people are is the first step in changing the government.
</p>
<p>
  Enter your address and phone number here and I’ll use your address to search Google Civic API to show you everyone that represents you in the United States government.
</p>
<p>
  [[ FORM ]]
</p>
<p>
  [[ SHOWS UP AFTER THEY CLICK SUBMIT ]]
</p>
<p>
  Now that we know who represents us, we should orient ourselves to what they do. Again, let’s just go straight to the source. Who do you want to follow? 
</p>
<p>
  [[ GALLARY OF OFFICIALS ]]
</p>
<p>
            Name, 
            Official Title,
            Poltical Party
</p>
<p>
  Next, select your favorite platforms and we'll automatically connect you to them so you know what they are up to.
</p>
<p>
  [[FB, Instagram, Twitter, Snapchat, Email Newsletter]]
</p>
<p>
  ----
</p>
<p>
  News sources still have their purpose! 
</p>
<p>
  Politicians will always spin things to paint themselves in the best light, so I want some third-party analysis. And I’m sure you do too. But, I don’t want to be inundated with all their noise and banter. I want to regulate the flow of information.
</p>
<p>
  The first step is deciding where you want to source your third-party analysis. I encourage you to subscribe to at least one or two that you aren't used to, just for a little diversity of thought.
</p>
<p>
  [[List of News Sites]]
</p>
<p>
  Next, what issues do you care about and how much do you care about each issue? This will help us prioritize getting you the news you care most about.
</p>
<p>
  [[Drag and Drop Issues from List to Pie Chart with editable allocation percentages]]
</p>
<p>
  Finally, how often do you want to be notified about the latest news - from every minute of every hour to a monthly summary and everything in between. 
</p>
<p>
  [[Select delivery frequency]]
</p>
<p>
  ----
</p>
<p>
  It's one thing to know what people are saying - but an entirely different thing to know how people are voting. 
</p>
<p>
  So, I also made nifty toolbar that shows you how your representative voted on bills you care about. 
</p>
<p>
  I didn't want it to be annoying, so it only shows up when you're on a social media or news website - when I care the most.
</p>
<p>
  [[Download Toolbar]]
</p>
<p>
  The toolbar makes it super easy to see how your elected officials are voting on bills related to issues you care about. 
</p>
<p>
  It also lets you call your elected official with a single click. If you like how they voted then you can call and tell them to keep up the good work! Trust me, they love hearing how good of a job they are doing. 
</p>
<p>
  And, if your elected official voted differently than how you want, make sure they know that too!
</p>
<p>
  It’s amazing how much time I spent posting about the news of the day on social media contrasted to how little time I actually spent doing anything. Now I can talk about what I did rather than merely complain and troll random strangers online.
</p>
<p>
  [[Share on Social Media buttons]]
</p>
<p>
  ----
</p>
<p>
  If that elected official still isn't stepping up it might be time to replace them. 
</p>
<p>
  In order to do that it's important to [[register to vote]]
</p>
<p>
  The toolbar will give you a notice when elections are coming up so you can get involved, donate, or maybe even run for something yourself!
</p>
<p>
  And, of course, we'll remind you when and where to vote. :)
</p>
<p>
  ----
</p>
<p>
  The last feature of the toolbar is meant to give you a voice.
</p>
<p>
  Congress has something like a 7% approval rating. Nearly all Americans agree that government is so polarized and partisan that it’s basically worthless. This makes us look stupid in the eyes of the world and Americans are smarter than that. 
</p>
<p>
  We agree on vastly more than we disagree on.
</p>
<p>
  The toolbar lets each person cast a single anonymous and public vote, and make a single statement on any issue they want.
</p>
<p>
  You can change your vote at any time. In fact, we encourage it. Soak in new information. Question assumptions. You should be discussing issues with friends, staying informed, ane evolving your perspectives. 
</p>
<p>
  Votes are recorded on the blockchain. So, you get all the security and privacy features along with the benefit of a decentralized system.
</p>
<p>
  Voter sentiment can be filtered and grouped by congressional district, state, national levels, as well as by political party. The full spectrum of political thought can be put on display through a signle statement that each voter is able to make when casting their vote.
</p>
<p>
  With widespread adoption and sufficient identity management, we could build an authoritative and decentralized voter sentiment model available to the public domain. 
</p>
<p>
  We can show the world that “we the people", on a district by district level, aren't as stupid as our government and political environment currently makes us look. 
</p>
<p>
  We are unified on most issues, and through this technology, we can prove it.
</p>
<p>
  ----
</p>
<p>
  VISION OF THE FUTURE
</p>
<p>
  This underlying technology has applications outside the political space. 
</p>
<p>
  Applying blockchain technology to voting system is an ideal use case that is issue agnostic and scales well. It works just as well electing a youth soccer team coach as it does the President of the United States. 
</p>
<p>
  Americans will insist on an online voting system in the future. An online voting platform with a proven track record and established goodwill with the public will be well positioned as an authoritative vendor to provide that solution.
</p>